swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains API endpoints in this codebase
    - view all their transactions for the current month
    - view the details of a transaction in another view
    - add, modify or delete information on a transaction
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Account User Module
      summary: User Accounts API
      description: API for fetching user accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User accounts retrieved successfully
          schema:
            $ref: '#/definitions/AccountsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/account/{idAccount}:
    get:
      security:
        - Bearer: []
      tags:
        - Account User Module
      summary: User account and its transactions API
      description: API for fetching transactions of a specific account 
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: idAccount
        description: ID of the account
        required: true
        type: integer
      produces:
        - application/json
      responses:
        '200':
          description: User account retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Bad Request
        '404':
          description: Account not found
        '500':
          description: Internal Server Error

  /user/account/{idAccount}/{idTransaction}:
    get:
      security:
        - Bearer: []
      tags:
        - Account User Module
      summary: Transactions User API
      description: API for fetching a specific transaction
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: idAccount
        description: ID of the account
        required: true
        type: string
      - in: path
        name: idTransaction
        description: ID of the transaction
        required: true
        type: string
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successfully
          schema:
            $ref: '#/definitions/TransactionInfosResponse'
        '400':
          description: Bad Request
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error       
    put:
      security:
        - Bearer: []
      tags:
        - Account User Module
      summary: Transactions User API
      description: API for updating a transaction's informations
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: idAccount
        description: ID of the account
        required: true
        type: string
      - in: path
        name: idTransaction
        description: ID of the transaction
        required: true
        type: string
      - in: body
        name: body
        description: Add user transaction's informations
        required: true
        schema:
          $ref: '#/definitions/TransactionInfos'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction's informations updated successfully
          schema:
            $ref: '#/definitions/TransactionInfosResponse'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionInfos:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
            category:
              type: string
              description: Category of the transaction
            note:
              type: string
              description: Note for the transaction
  AccountsResponse:
    type: object
    properties:
      status:
        type: integer
        description: Status of the response
      message:
        type: string
        description: Description of the response status
      body:
        type: object
        properties:
          accounts:
            type: array
            items: 
              type: object
              properties:
                id:
                  type: integer
                  description: ID of the account
                balance:
                  type: number
                  description: Balance available on the account             
  TransactionsResponse: 
    type: object
    properties:
      status:
        type: integer
        description: Status of the response
      message:
        type: string
        description: Description of the response status
      body:
        type: object 
        properties:
          transactions:
            type: array
            items:
              properties:
                id: 
                  type: integer
                  description: ID of the transaction
                date:
                  type: string
                  format: date-time  
                  description: Date of the transaction
                description:
                  type: string
                  description: Description of the transaction
                amount:
                  type: number
                  description: Amount of the transaction
                remaining_balance:
                  type: number
                  description: Remaining balance after the transaction
  TransactionInfosResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transaction_type:
            type: string
            description: Type of the transaction
          category:
            type: string
            description: Category of the transaction
          note:
            type: string
            description: Note for the transaction